map_init:
  center:
    lat: 0
    lng: 0
  zoom: 1
  minzoom: 1
  maxzoom: 4
  url: './tiles/{z}/{x}/{y}.png'
  attribution: '&copy;'
  nowrap: true
tile_image:
  tile_size: 256
  image_path: 'examples/oblique_aerial_image.tif'
