map_init:
  center:
    lat: 0
    lng: 0
  zoom: 1
  minzoom: 1
  maxzoom: 4
  url: './tiles/{z}/{x}/{y}.png'
  # url: 'http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png'
  attribution: '&copy;'
  nowrap: true
tile_image:
  tile_size: 256
  image_path: 'examples/oblique_aerial_image.tif'
markers:
  - x: 2286
    y: 1546
    type: playground
  - x: 1330
    y: 382
    type: pool
  - x: 2480
    y: 1248
    type: building
  - x: 2636
    y: 1900
    type: tree
  - x: 842
    y: 753
    type: car
  - x: 2905
    y: 1692
    type: car
  - x: 2411
    y: 606
    type: tree
  - x: 727
    y: 1651
    type: tree
legend:
  pool:
    icon: jellyfish-svgrepo-com.svg
  playground:
    icon: fish-svgrepo-com.svg
  building:
    icon: lobster-svgrepo-com.svg
  car:
    icon: octopus-svgrepo-com.svg
  tree:
    icon: shark-svgrepo-com.svg
