map_init:
  center:
    lat: 39.209272
    lng: -76.797118
  zoom: 11
  maxzoom: 18
  url: 'http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png'
  attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
tile_image:
  tile_size: 256
  image_path: 'examples/oblique_aerial_image.tif'
